-- create or replace function lib.query_any( any boolean, document jsonb )
-- returns text
-- language plpgsql as $$
-- declare
-- begin
-- end;
-- $$;
--
--
-- drop function lib.query_eval( text, jsonb );
-- create or replace function lib.query_eval( text, jsonb )
-- returns boolean
-- language plpgsql as $$
-- declare
--   _result record;
-- begin
--   execute format('select (%s) as result', $1 ) into _result using $2;
--   return _result.result;
-- exception when others then return false;
-- end;
-- $$;